"""`GenericGraphStorageAdapter` — the generic (backend-agnostic) implementation of the graph-storage task contract. Thread-3 packaging: the GENERIC adapter impl is the dominant case and lives in the dep-light interface lib, reused across all compatible backend tools. Its job is **wire-input normalization + forwarding**: accept wire dicts or typed objects at the task boundary, hand the tool purely-typed arguments, pass typed results through (they wire-encode at the worker boundary).

Docs: https://cj-mills.github.io/cjm-graph-storage-adapter-interfacegeneric.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/generic.ipynb.

# %% auto #0
__all__ = ['ensure_node', 'ensure_edge', 'ensure_context', 'ensure_source_ref', 'ensure_node_query', 'ensure_edge_query',
           'ensure_raw_query', 'GenericGraphStorageAdapter']

# %% ../nbs/generic.ipynb #dc33e839
from typing import Any, Dict, List, Optional

from cjm_context_graph_primitives.provenance import SourceRef
from cjm_context_graph_primitives.graph import GraphNode, GraphEdge, GraphContext
from cjm_context_graph_primitives.query import (
    NodeQuery, EdgeQuery, RawQuery,
    NodeQueryResult, EdgeQueryResult, RawQueryResult,
)

from .adapter import GraphStorageAdapter

# %% ../nbs/generic.ipynb #a40755a2
def ensure_node(
    value: Any,  # GraphNode or its wire dict
) -> GraphNode:  # Typed node
    """Normalize a wire dict to a `GraphNode` (typed values pass through)."""
    return value if isinstance(value, GraphNode) else GraphNode.from_dict(value)

# %% ../nbs/generic.ipynb #38c76e24
def ensure_edge(
    value: Any,  # GraphEdge or its wire dict
) -> GraphEdge:  # Typed edge
    """Normalize a wire dict to a `GraphEdge` (typed values pass through)."""
    return value if isinstance(value, GraphEdge) else GraphEdge.from_dict(value)

# %% ../nbs/generic.ipynb #95903dd8
def ensure_context(
    value: Any,  # GraphContext or its wire dict
) -> GraphContext:  # Typed context
    """Normalize a wire dict to a `GraphContext` (typed values pass through)."""
    return value if isinstance(value, GraphContext) else GraphContext.from_dict(value)

# %% ../nbs/generic.ipynb #ed8c50f2
def ensure_source_ref(
    value: Any,  # SourceRef or its wire dict
) -> SourceRef:  # Typed source ref
    """Normalize a wire dict to a `SourceRef` (typed values pass through)."""
    return value if isinstance(value, SourceRef) else SourceRef.from_dict(value)

# %% ../nbs/generic.ipynb #8b197c3c
def ensure_node_query(
    value: Any,  # NodeQuery or its tagged wire dict
) -> NodeQuery:  # Typed query
    """Normalize a tagged wire dict to a `NodeQuery` (typed values pass through)."""
    return value if isinstance(value, NodeQuery) else NodeQuery.from_dict(value)

# %% ../nbs/generic.ipynb #38966bcc
def ensure_edge_query(
    value: Any,  # EdgeQuery or its tagged wire dict
) -> EdgeQuery:  # Typed query
    """Normalize a tagged wire dict to an `EdgeQuery` (typed values pass through)."""
    return value if isinstance(value, EdgeQuery) else EdgeQuery.from_dict(value)

# %% ../nbs/generic.ipynb #a84aae31
def ensure_raw_query(
    value: Any,  # RawQuery or its tagged wire dict
) -> RawQuery:  # Typed query
    """Normalize a tagged wire dict to a `RawQuery` (typed values pass through)."""
    return value if isinstance(value, RawQuery) else RawQuery.from_dict(value)

# %% ../nbs/generic.ipynb #5488d740
class GenericGraphStorageAdapter(GraphStorageAdapter):
    """Generic graph-storage adapter: normalize wire inputs, forward to the
    bound tool, pass typed results through.

    Works against ANY tool satisfying `GraphStorageToolProtocol` — the
    backend owns translation, so nothing here is backend-specific.
    """

    def add_nodes(self, nodes: List[Any]) -> List[str]:
        """Bulk-create nodes."""
        return self.tool.add_nodes([ensure_node(n) for n in nodes])

    def add_edges(self, edges: List[Any]) -> List[str]:
        """Bulk-create edges."""
        return self.tool.add_edges([ensure_edge(e) for e in edges])

    def get_node(self, node_id: str) -> Optional[GraphNode]:
        """Fetch a single node by id."""
        return self.tool.get_node(node_id)

    def get_edge(self, edge_id: str) -> Optional[GraphEdge]:
        """Fetch a single edge by id."""
        return self.tool.get_edge(edge_id)

    def get_context(self, node_id: str, depth: int = 1,
                    filter_labels: Optional[List[str]] = None) -> GraphContext:
        """Fetch a node's neighborhood subgraph."""
        return self.tool.get_context(node_id, depth=depth, filter_labels=filter_labels)

    def find_nodes_by_source(self, source_ref: Any) -> List[GraphNode]:
        """Reverse provenance lookup (content-hash-primary)."""
        return self.tool.find_nodes_by_source(ensure_source_ref(source_ref))

    def find_nodes_by_label(self, label: str, limit: int = 100) -> List[GraphNode]:
        """Fetch nodes by label."""
        return self.tool.find_nodes_by_label(label, limit=limit)

    def query_nodes(self, query: Any) -> NodeQueryResult:
        """Execute a typed node query."""
        return self.tool.query_nodes(ensure_node_query(query))

    def query_edges(self, query: Any) -> EdgeQueryResult:
        """Execute a typed edge query."""
        return self.tool.query_edges(ensure_edge_query(query))

    def raw_query(self, query: Any) -> RawQueryResult:
        """Execute the marked, backend-coupled raw escape."""
        return self.tool.raw_query(ensure_raw_query(query))

    def update_node(self, node_id: str, properties: Dict[str, Any]) -> bool:
        """Merge properties into a node."""
        return self.tool.update_node(node_id, properties)

    def update_edge(self, edge_id: str, properties: Dict[str, Any]) -> bool:
        """Merge properties into an edge."""
        return self.tool.update_edge(edge_id, properties)

    def delete_nodes(self, node_ids: List[str], cascade: bool = True) -> int:
        """Bulk-delete nodes."""
        return self.tool.delete_nodes(node_ids, cascade=cascade)

    def delete_edges(self, edge_ids: List[str]) -> int:
        """Bulk-delete edges."""
        return self.tool.delete_edges(edge_ids)

    def get_schema(self) -> Dict[str, Any]:
        """Report the stored graph's schema."""
        return self.tool.get_schema()

    def integrity_check(self) -> Dict[str, Any]:
        """Backend self-check (G3 institutionalized)."""
        return self.tool.integrity_check()

    def import_graph(self, graph_data: Any, merge_strategy: str = "overwrite") -> Dict[str, int]:
        """Bulk-import a subgraph."""
        return self.tool.import_graph(ensure_context(graph_data), merge_strategy=merge_strategy)

    def export_graph(self, filter_query: Optional[Any] = None) -> GraphContext:
        """Export the graph (optionally filtered by a typed node query)."""
        fq = ensure_node_query(filter_query) if filter_query is not None else None
        return self.tool.export_graph(fq)
